/**
 * @author generated by eTrice
 *
 * Utils File of ActorClass ADAS_Controller
 *
 */

#ifndef _TEMPLATEMODEL_ADAS_CONTROLLER_UTILS_H_
#define _TEMPLATEMODEL_ADAS_CONTROLLER_UTILS_H_

#include "TemplateModel/ADAS_Controller.h"

/*
 * access macros for ports, operations and attributes
*/

/* simple event ports */
#define dataPortB_receivedData(data) PSendDataPort_receivedData(&self->constData->dataPortB, data)
#define relayPortA_sendData(data) PSendDataConjPort_sendData(&self->constData->relayPortA, data)
#define relayPortA_forRingControl() PSendDataConjPort_forRingControl(&self->constData->relayPortA)
#define relayPortB_sendData(data) PSendDataConjPort_sendData(&self->constData->relayPortB, data)
#define relayPortB_forRingControl() PSendDataConjPort_forRingControl(&self->constData->relayPortB)
#define relayPortC_sendData(data) PSendDataConjPort_sendData(&self->constData->relayPortC, data)
#define relayPortC_forRingControl() PSendDataConjPort_forRingControl(&self->constData->relayPortC)

/* data receive ports */

/* data send ports */

/* saps */

/* replicated event ports */

/* services */

/* operations */
#define ALK() ADAS_Controller_ALK(self)
#define ACC() ADAS_Controller_ACC(self)
#define ChoicePoint0(dist, velo, tl, cnum) ADAS_Controller_ChoicePoint0(self, dist, velo, tl, cnum)
#define AEB() ADAS_Controller_AEB(self)

/* attributes */
#define str (self->str)
#define retain_str (self->retain_str)
#define send_str (self->send_str)
#define temp_string (self->temp_string)
#define velocity (self->velocity)
#define distance (self->distance)
#define colliderNum (self->colliderNum)
#define steering (self->steering)
#define trafficLight (self->trafficLight)

/* port operations */

#endif /* _TEMPLATEMODEL_ADAS_CONTROLLER_UTILS_H_ */

