/**
 * @author generated by eTrice
 *
 * Utils File of ActorClass ALK
 *
 */

#ifndef _TEMPLATEMODEL_ALK_UTILS_H_
#define _TEMPLATEMODEL_ALK_UTILS_H_

#include "TemplateModel/ALK.h"

/*
 * access macros for ports, operations and attributes
*/

/* simple event ports */
#define recvPort_receivedData(data) PSendDataPort_receivedData(&self->constData->recvPort, data)

/* data receive ports */

/* data send ports */

/* saps */

/* replicated event ports */

/* services */

/* operations */
#define ALKchoicePoint0(s_code) ALK_ALKchoicePoint0(self, s_code)
#define lane_change() ALK_lane_change(self)

/* attributes */
#define str (self->str)
#define send_str (self->send_str)
#define temp_string (self->temp_string)
#define velocity (self->velocity)
#define distance (self->distance)
#define colliderNum (self->colliderNum)
#define colliderNum_str (self->colliderNum_str)
#define steering (self->steering)
#define trafficLight (self->trafficLight)
#define situation_code (self->situation_code)

/* port operations */

#endif /* _TEMPLATEMODEL_ALK_UTILS_H_ */

