/**
 * @author generated by eTrice
 *
 * Utils File of ActorClass Gateway
 *
 */

#ifndef _TEMPLATEMODEL_GATEWAY_UTILS_H_
#define _TEMPLATEMODEL_GATEWAY_UTILS_H_

#include "TemplateModel/Gateway.h"

/*
 * access macros for ports, operations and attributes
*/

/* simple event ports */
#define ctrl_connect(data) PTcpControlConjPort_connect(&self->constData->ctrl, data)
#define ctrl_disconnect() PTcpControlConjPort_disconnect(&self->constData->ctrl)
#define payload_dataPackage(data) PTcpPayloadConjPort_dataPackage(&self->constData->payload, data)
#define dataPortA_sendData(data) PSendDataConjPort_sendData(&self->constData->dataPortA, data)
#define dataPortA_forRingControl() PSendDataConjPort_forRingControl(&self->constData->dataPortA)

/* data receive ports */

/* data send ports */

/* saps */

/* replicated event ports */

/* services */

/* operations */
#define sendPayloadString(data) Gateway_sendPayloadString(self, data)

/* attributes */
#define str1 (self->str1)
#define str2 (self->str2)
#define situation_code (self->situation_code)
#define temp_string (self->temp_string)

/* port operations */

#endif /* _TEMPLATEMODEL_GATEWAY_UTILS_H_ */

