/**
 * @author generated by eTrice
 *
 * Source File of ActorClass Gateway
 *
 */

#include "Gateway.h"

#include "modelbase/etActor.h"
#include "debugging/etLogger.h"
#include "debugging/etMSCLogger.h"
#include "etUnit/etUnit.h"
#include "base/etMemory.h"

#include "TemplateModel/PSendData.h"
#include "room/basic/service/tcp/PTcpControl.h"
#include "room/basic/service/tcp/PTcpPayload.h"

#include "Gateway_Utils.h"

LARGE_INTEGER starttime,freq,end; //added by kkr
int totalcount=0;//added by kkr
int AEBcount=0;//added by kkr
int ACCcount=0;//added by kkr
int ALKcount=0;//added by kkr
double AEBtime=0;//added by kkr
double ACCtime=0;//added by kkr
double ALKtime=0;//added by kkr
double MAXACCtime=0;//added by kkr
double MAXAEBtime=0;//added by kkr
double MAXALKtime=0;//added by kkr

/* interface item IDs */
enum interface_items {
	IFITEM_ctrl = 1,
	IFITEM_payload = 2,
	IFITEM_dataPortA = 3
};

/* state IDs */
enum state_ids {
	NO_STATE = 0,
	STATE_TOP = 1,
	STATE_Connecting = 2,
	STATE_Connected = 3,
	STATE_ADAScontroller = 4,
	STATE_MAX = 5
};

/* transition chains */
enum ChainIDs {
	CHAIN_TRANS_INITIAL_TO__Connecting = 1,
	CHAIN_TRANS_tr0_FROM_Connecting_TO_Connected_BY_connectedctrl = 2,
	CHAIN_TRANS_tr1_FROM_Connected_TO_ADAScontroller_BY_dataPackagepayload = 3,
	CHAIN_TRANS_tr2_FROM_ADAScontroller_TO_Connected_BY_receivedDatadataPortA = 4
};

/* triggers */
enum triggers {
	POLLING = 0,
	TRIG_ctrl__connected = IFITEM_ctrl + EVT_SHIFT*PTcpControl_OUT_connected,
	TRIG_ctrl__disconnected = IFITEM_ctrl + EVT_SHIFT*PTcpControl_OUT_disconnected,
	TRIG_ctrl__error = IFITEM_ctrl + EVT_SHIFT*PTcpControl_OUT_error,
	TRIG_payload__dataPackage = IFITEM_payload + EVT_SHIFT*PTcpPayload_OUT_dataPackage,
	TRIG_dataPortA__receivedData = IFITEM_dataPortA + EVT_SHIFT*PSendData_OUT_receivedData
};

/* state names */
static char* stateStrings[] = {"<no state>","<top>","Connecting",
"Connected",
"ADAScontroller"
};

static void setState(Gateway* self, etInt16 new_state) {
	self->state = new_state;
	ET_MSC_LOGGER_CHANGE_STATE(self->constData->instName, stateStrings[new_state])
}

static etInt16 getState(Gateway* self) {
	return self->state;
}

/* Entry and Exit Codes */
static void entry_Connecting(Gateway* self) {
	printf("Gateway: connecting to port %d\n", 6666);
	DTcpControl config = {"localhost", 6666};
	ctrl_connect(&config);
}
static void entry_Connected(Gateway* self) {
	// 2. client -> server
	// when it first send usless data
	// 5. client -> server(changed data by ADAS)
	sendPayloadString(str1);
	if(totalcount!=0){//added by kkr
		LARGE_INTEGER end;
		QueryPerformanceCounter(&end);
		__int64 elapsed = end.QuadPart- starttime.QuadPart;
		double duringtime = (double)elapsed / (double)freq.QuadPart*1000;
		if(situation_code[0]=='G'||situation_code[0]=='N'){
			ACCtime+=duringtime;
			ACCcount++;
			if(duringtime>MAXACCtime){
				MAXACCtime=duringtime;
			}
		}
		else if(situation_code[0]=='E'){
			AEBcount++;
			AEBtime+=duringtime;
			if(duringtime>MAXAEBtime){
				MAXAEBtime=duringtime;
			}
		}
		else if(situation_code[0]=='L'){
			ALKtime+=duringtime;
			ALKcount++;
			if(duringtime>MAXALKtime){
				MAXALKtime=duringtime;
			}
		}
		totalcount++;
		if(totalcount==1850){
			FILE *fp = fopen("extime.txt", "a");
			fprintf(fp, "%d, ", ACCcount);
			fprintf(fp, "%f, ", ACCtime);
			fprintf(fp, "%f, ", MAXACCtime);
			fprintf(fp, "%f, ",ACCtime/ACCcount);
			fprintf(fp, "%d, ", AEBcount);
			fprintf(fp, "%f, ", AEBtime);
			fprintf(fp, "%f, ", MAXAEBtime);
			fprintf(fp, "%f, ",AEBtime/AEBcount);
			fprintf(fp, "%d, ", ALKcount);
			fprintf(fp, "%f, ", ALKtime);
			fprintf(fp, "%f, ", MAXAEBtime);
			fprintf(fp, "%f\n",ALKtime/ALKcount);
			fclose (fp);
			exit(0);
		}
	}
	else if(totalcount==0){
		totalcount++;
	}
}
static void entry_ADAScontroller(Gateway* self) {
	// 3. gateway -> Controller
	DDataBuffer buf;
	strcpy(buf.buffer, str2);
	dataPortA_sendData(&buf);
}

/* Action Codes */

static void action_TRANS_tr1_FROM_Connected_TO_ADAScontroller_BY_dataPackagepayload(Gateway* self, const InterfaceItemBase* ifitem, DTcpPayload* data) {
    // 1. server -> ROOM(gateway)
    // 1. server -> ROOM(gateway) RingControl
    strcpy(str2, data->data);
	QueryPerformanceFrequency(&freq);
	QueryPerformanceCounter(&starttime);
}
static void action_TRANS_tr2_FROM_ADAScontroller_TO_Connected_BY_receivedDatadataPortA(Gateway* self, const InterfaceItemBase* ifitem, DDataBuffer* data) {
    // 4. Controller -> Gateway
    strcpy(str1, data->buffer);
    if(isalpha(str1[6]))
    	situation_code[0]=str1[6];
    else
    	situation_code[0]=str1[7];
}

/* State Switch Methods */
/**
 * calls exit codes while exiting from the current state to one of its
 * parent states while remembering the history
 * @param current__et - the current state
 * @param to - the final parent state
 */
static void exitTo(Gateway* self, etInt16 current__et, etInt16 to) {
	while (current__et!=to) {
		switch (current__et) {
			case STATE_Connecting:
				self->history[STATE_TOP] = STATE_Connecting;
				current__et = STATE_TOP;
				break;
			case STATE_Connected:
				self->history[STATE_TOP] = STATE_Connected;
				current__et = STATE_TOP;
				break;
			case STATE_ADAScontroller:
				self->history[STATE_TOP] = STATE_ADAScontroller;
				current__et = STATE_TOP;
				break;
			default:
				/* should not occur */
				break;
		}
	}
}

/**
 * calls action, entry and exit codes along a transition chain. The generic data are cast to typed data
 * matching the trigger of this chain. The ID of the final state is returned
 * @param chain__et - the chain ID
 * @param generic_data__et - the generic data pointer
 * @return the +/- ID of the final state either with a positive sign, that indicates to execute the state's entry code, or a negative sign vice versa
 */
static etInt16 executeTransitionChain(Gateway* self, int chain__et, const InterfaceItemBase* ifitem, void* generic_data__et) {
	switch (chain__et) {
		case CHAIN_TRANS_INITIAL_TO__Connecting:
		{
			return STATE_Connecting;
		}
		case CHAIN_TRANS_tr0_FROM_Connecting_TO_Connected_BY_connectedctrl:
		{
			return STATE_Connected;
		}
		case CHAIN_TRANS_tr1_FROM_Connected_TO_ADAScontroller_BY_dataPackagepayload:
		{
			DTcpPayload* data = ((DTcpPayload*) generic_data__et);
			action_TRANS_tr1_FROM_Connected_TO_ADAScontroller_BY_dataPackagepayload(self, ifitem, data);
			return STATE_ADAScontroller;
		}
		case CHAIN_TRANS_tr2_FROM_ADAScontroller_TO_Connected_BY_receivedDatadataPortA:
		{
			DDataBuffer* data = ((DDataBuffer*) generic_data__et);
			action_TRANS_tr2_FROM_ADAScontroller_TO_Connected_BY_receivedDatadataPortA(self, ifitem, data);
			return STATE_Connected;
		}
			default:
				/* should not occur */
				break;
	}
	return NO_STATE;
}

/**
 * calls entry codes while entering a state's history. The ID of the final leaf state is returned
 * @param state__et - the state which is entered
 * @return - the ID of the final leaf state
 */
static etInt16 enterHistory(Gateway* self, etInt16 state__et) {
	etBool skip_entry__et = ET_FALSE;
	if (state__et >= STATE_MAX) {
		state__et = (etInt16) (state__et - STATE_MAX);
		skip_entry__et = ET_TRUE;
	}
	while (ET_TRUE) {
		switch (state__et) {
			case STATE_Connecting:
				if (!(skip_entry__et)) entry_Connecting(self);
				/* in leaf state: return state id */
				return STATE_Connecting;
			case STATE_Connected:
				if (!(skip_entry__et)) entry_Connected(self);
				/* in leaf state: return state id */
				return STATE_Connected;
			case STATE_ADAScontroller:
				if (!(skip_entry__et)) entry_ADAScontroller(self);
				/* in leaf state: return state id */
				return STATE_ADAScontroller;
			case STATE_TOP:
				state__et = self->history[STATE_TOP];
				break;
			default:
				/* should not occur */
				break;
		}
		skip_entry__et = ET_FALSE;
	}
	/* return NO_STATE; // required by CDT but detected as unreachable by JDT because of while (true) */
}

static void Gateway_executeInitTransition(Gateway* self) {
	int chain__et = CHAIN_TRANS_INITIAL_TO__Connecting;
	etInt16 next__et = executeTransitionChain(self, chain__et, NULL, NULL);
	next__et = enterHistory(self, next__et);
	setState(self, next__et);
}

/* receiveEvent contains the main implementation of the FSM */
static void Gateway_receiveEventInternal(Gateway* self, InterfaceItemBase* ifitem, int localId, int evt, void* generic_data__et) {
	int trigger__et = localId + EVT_SHIFT*evt;
	int chain__et = NOT_CAUGHT;
	etInt16 catching_state__et = NO_STATE;
	((void)trigger__et);	/* avoids unused warning */

	if (!handleSystemEvent(ifitem, evt, generic_data__et)) {
		switch (getState(self)) {
		    case STATE_Connecting:
		        switch(trigger__et) {
		                case TRIG_ctrl__connected:
		                    {
		                        chain__et = CHAIN_TRANS_tr0_FROM_Connecting_TO_Connected_BY_connectedctrl;
		                        catching_state__et = STATE_TOP;
		                    }
		                break;
		                default:
		                    /* should not occur */
		                    break;
		        }
		        break;
		    case STATE_Connected:
		        switch(trigger__et) {
		                case TRIG_payload__dataPackage:
		                    {
		                        chain__et = CHAIN_TRANS_tr1_FROM_Connected_TO_ADAScontroller_BY_dataPackagepayload;
		                        catching_state__et = STATE_TOP;
		                    }
		                break;
		                default:
		                    /* should not occur */
		                    break;
		        }
		        break;
		    case STATE_ADAScontroller:
		        switch(trigger__et) {
		                case TRIG_dataPortA__receivedData:
		                    {
		                        chain__et = CHAIN_TRANS_tr2_FROM_ADAScontroller_TO_Connected_BY_receivedDatadataPortA;
		                        catching_state__et = STATE_TOP;
		                    }
		                break;
		                default:
		                    /* should not occur */
		                    break;
		        }
		        break;
		    default:
		        /* should not occur */
		        break;
		}
	}
	if (chain__et != NOT_CAUGHT) {
		exitTo(self, getState(self), catching_state__et);
		{
			etInt16 next__et = executeTransitionChain(self, chain__et, ifitem, generic_data__et);
			next__et = enterHistory(self, next__et);
			setState(self, next__et);
		}
	}
}
static void Gateway_receiveEvent(Gateway* self, InterfaceItemBase* ifitem, int evt, void* generic_data__et) {
	int localId = (ifitem==NULL)? 0 : ifitem->localId;
	Gateway_receiveEventInternal(self, ifitem, localId, evt, generic_data__et);
}

void Gateway_init(Gateway* self){
	ET_MSC_LOGGER_SYNC_ENTRY("Gateway", "init")
	self->state = STATE_TOP;
	{
		int i;
		for (i=0; i<GATEWAY_HISTORY_SIZE; ++i)
			self->history[i] = NO_STATE;
	}
	Gateway_executeInitTransition(self);
	ET_MSC_LOGGER_SYNC_EXIT
}


void Gateway_receiveMessage(void* self, const void* ifitem, const etMessage* msg){
	ET_MSC_LOGGER_SYNC_ENTRY("Gateway", "_receiveMessage")
	Gateway_receiveEvent(self, (etPort*)ifitem, msg->evtID, (void*)(((char*)msg)+MEM_CEIL(sizeof(etMessage))));

	ET_MSC_LOGGER_SYNC_EXIT
}


/*--------------------- user constructor/destructor ---------------------*/

/*--------------------- operations ---------------------*/
 void Gateway_sendPayloadString(Gateway* self, char* data) {
	DTcpPayload package;
	DTcpPayload_setAsString(&package, data);
	payload_dataPackage(&package);
}

