/**
 * @author generated by eTrice
 *
 * Source File of Node node with SubSystem subSystemRef
 *
 */

#include <stdio.h>
#include <string.h>


#include "node_subSystemRef.h"

#include "debugging/etLogger.h"
#include "debugging/etMSCLogger.h"
#include "debugging/etDataLogger.h"
#include "messaging/etSystemProtocol.h"
#include "osal/etTimer.h"
#include "osal/etSema.h"
#include "runtime/etRuntime.h"
#include "etRuntimeConfig.h"


/* data for Node node with SubSystem subSystemRef */
typedef struct node_subSystemRef {
	char *name;
	volatile int shutdownRequest;
} node_subSystemRef;

static node_subSystemRef node_subSystemRefInst = {"node_subSystemRef", 0};

static void node_subSystemRef_initActorInstances(void);
static void node_subSystemRef_constructActorInstances(void);

/* include instances for all classes */
#include "node_subSystemRef_Inst.h"
#include "node_subSystemRef_Disp.h"

static void node_subSystemRef_initMessageServices(void) {
	ET_MSC_LOGGER_SYNC_ENTRY("node_subSystemRef", "initMessageServices")
	{
		etTime interval;

		/* initialization of all message services */
		etMessageService_init(
			&msgService_PALKThread,
			msgBuffer_PALKThread,
			PALKTHREAD_POOL_SIZE,
			PALKTHREAD_BLOCK_SIZE,
			1024,
			0,
			interval,
			MsgDispatcher_PALKThread_receiveMessage,
			EXECMODE_BLOCKED,
			6);//할당할 CPU의 숫자를 넣어야한다. added by kkr

		etMessageService_init(
			&msgService_PAEBThread,
			msgBuffer_PAEBThread,
			PAEBTHREAD_POOL_SIZE,
			PAEBTHREAD_BLOCK_SIZE,
			1024,
			1,
			interval,
			MsgDispatcher_PAEBThread_receiveMessage,
			EXECMODE_BLOCKED,
			6);//할당할 CPU의 숫자를 넣어야한다. added by kkr

		interval.sec = 0;
		interval.nSec = 100000000;
		etMessageService_init(
			&msgService_DefaultPhysicalThread,
			msgBuffer_DefaultPhysicalThread,
			DEFAULTPHYSICALTHREAD_POOL_SIZE,
			DEFAULTPHYSICALTHREAD_BLOCK_SIZE,
			1024,
			0,
			interval,
			MsgDispatcher_DefaultPhysicalThread_receiveMessage,
			EXECMODE_MIXED,
			1);//할당할 CPU의 숫자를 넣어야한다. added by kkr

		etMessageService_init(
			&msgService_GateThread,
			msgBuffer_GateThread,
			GATETHREAD_POOL_SIZE,
			GATETHREAD_BLOCK_SIZE,
			1024,
			0,
			interval,
			MsgDispatcher_GateThread_receiveMessage,
			EXECMODE_BLOCKED,
			4);//할당할 CPU의 숫자를 넣어야한다. added by kkr

		etMessageService_init(
			&msgService_ControlThread,
			msgBuffer_ControlThread,
			CONTROLTHREAD_POOL_SIZE,
			CONTROLTHREAD_BLOCK_SIZE,
			1024,
			0,
			interval,
			MsgDispatcher_ControlThread_receiveMessage,
			EXECMODE_BLOCKED,
			5);//할당할 CPU의 숫자를 넣어야한다. added by kkr

		etMessageService_init(
			&msgService_PACCThread,
			msgBuffer_PACCThread,
			PACCTHREAD_POOL_SIZE,
			PACCTHREAD_BLOCK_SIZE,
			1024,
			2,
			interval,
			MsgDispatcher_PACCThread_receiveMessage,
			EXECMODE_BLOCKED,
			6); //할당할 CPU의 숫자를 넣어야한다. added by kkr

	}

	ET_MSC_LOGGER_SYNC_EXIT
}

static void node_subSystemRef_startMessageServices(void) {
	ET_MSC_LOGGER_SYNC_ENTRY("node_subSystemRef", "startMessageServices")

	etMessageService_start(&msgService_PALKThread);
	etMessageService_start(&msgService_PAEBThread);
	etMessageService_start(&msgService_DefaultPhysicalThread);
	etMessageService_start(&msgService_GateThread);
	etMessageService_start(&msgService_ControlThread);
	etMessageService_start(&msgService_PACCThread);

	ET_MSC_LOGGER_SYNC_EXIT
}

static void node_subSystemRef_stopMessageServices(void) {
	ET_MSC_LOGGER_SYNC_ENTRY("node_subSystemRef", "stopMessageServices")

	etMessageService_stop(&msgService_DefaultPhysicalThread);
	etMessageService_stop(&msgService_GateThread);
	etMessageService_stop(&msgService_ControlThread);
	etMessageService_stop(&msgService_PAEBThread);
	etMessageService_stop(&msgService_PACCThread);
	etMessageService_stop(&msgService_PALKThread);

	ET_MSC_LOGGER_SYNC_EXIT
}

static void node_subSystemRef_destroyMessageServices(void) {
	ET_MSC_LOGGER_SYNC_ENTRY("node_subSystemRef", "destroyMessageServices")

	etMessageService_destroy(&msgService_DefaultPhysicalThread);
	etMessageService_destroy(&msgService_GateThread);
	etMessageService_destroy(&msgService_ControlThread);
	etMessageService_destroy(&msgService_PAEBThread);
	etMessageService_destroy(&msgService_PACCThread);
	etMessageService_destroy(&msgService_PALKThread);

	ET_MSC_LOGGER_SYNC_EXIT
}

void node_subSystemRef_init(void) {
	ET_MSC_LOGGER_SYNC_ENTRY("node_subSystemRef", "init")
	etLogger_logInfoF("%s_init", node_subSystemRefInst.name);

	/* construct all actors */
	node_subSystemRef_constructActorInstances();

	/* initialization of all message services */
	node_subSystemRef_initMessageServices();

	/* init all actors */
	node_subSystemRef_initActorInstances();


	ET_MSC_LOGGER_SYNC_EXIT
}

void node_subSystemRef_start(void) {
	ET_MSC_LOGGER_SYNC_ENTRY("node_subSystemRef", "start")
	etLogger_logInfoF("%s_start", node_subSystemRefInst.name);
	node_subSystemRef_startMessageServices();
	ET_MSC_LOGGER_SYNC_EXIT
}

void node_subSystemRef_run(etBool runAsTest) {
#ifdef ET_RUNNER_ACTIVATE
	ET_MSC_LOGGER_SYNC_ENTRY("node_subSystemRef", "run")

	if (runAsTest) {
		etSema_waitForWakeup(etRuntime_getTerminateSemaphore());
	}
	else {
		printf("type quit to exit\n");
		fflush(stdout);
		while (ET_TRUE) {
			char line[64];

			if (fgets(line, 64, stdin) != NULL) {
				if (strncmp(line, "quit", 4)==0)
					break;
			}
		}
	}

	ET_MSC_LOGGER_SYNC_EXIT
#endif
}

void node_subSystemRef_stop(void){
	ET_MSC_LOGGER_SYNC_ENTRY("node_subSystemRef", "stop")
	etLogger_logInfoF("%s_stop", node_subSystemRefInst.name);

	node_subSystemRef_stopMessageServices();

	ET_MSC_LOGGER_SYNC_EXIT
}

void node_subSystemRef_destroy(void){
	ET_MSC_LOGGER_SYNC_ENTRY("node_subSystemRef", "destroy")
	etLogger_logInfoF("%s_destroy", node_subSystemRefInst.name);

	ATcpClient_dtor(&_LogSys_subSystemRef_topActor_TCPClient);

	node_subSystemRef_destroyMessageServices();

	ET_MSC_LOGGER_SYNC_EXIT
}

void node_subSystemRef_shutdown(void){
	ET_MSC_LOGGER_SYNC_ENTRY("node_subSystemRef", "shutdown")
	etLogger_logInfoF("%s_shutdown", node_subSystemRefInst.name);

	node_subSystemRefInst.shutdownRequest = 1;

	ET_MSC_LOGGER_SYNC_EXIT
}


static void node_subSystemRef_constructActorInstances(void){
	ET_MSC_LOGGER_SYNC_ENTRY("node_subSystemRef", "constructActorInstances")

	ATcpClient_ctor(&_LogSys_subSystemRef_topActor_TCPClient);

	ET_MSC_LOGGER_SYNC_EXIT
}

static void node_subSystemRef_initActorInstances(void){
	ET_MSC_LOGGER_SYNC_ENTRY("node_subSystemRef", "initActorInstances")

	TopActor_init(&_LogSys_subSystemRef_topActor);
	ATcpClient_init(&_LogSys_subSystemRef_topActor_TCPClient);
	Gateway_init(&_LogSys_subSystemRef_topActor_gateway);
	ADAS_Controller_init(&_LogSys_subSystemRef_topActor_controller);
	AEB_init(&_LogSys_subSystemRef_topActor_AutoEmergencyBraking);
	ACC_init(&_LogSys_subSystemRef_topActor_AdaptiveCruiseControl);
	ALK_init(&_LogSys_subSystemRef_topActor_AutoLaneKeeping);
	ATimingService_init(&_LogSys_subSystemRef_timingService);

	ET_MSC_LOGGER_SYNC_EXIT
}
