/**
 * @author generated by eTrice
 *
 * Source File of ProtocolClass PSendData
 * 
 */

#include "PSendData.h"
#include "debugging/etMSCLogger.h"
#include "PSendData_Utils.h"


/*--------------------- port methods */

void PSendDataPort_receivedData(const PSendDataPort* self, DDataBuffer* data__et) {
	ET_MSC_LOGGER_SYNC_ENTRY("PSendDataPort", "receivedData")
		etPort_sendMessage(self, PSendData_OUT_receivedData, sizeof(DDataBuffer), data__et);
		ET_MSC_LOGGER_ASYNC_OUT(self->myInstName, "receivedData", self->peerInstName)
	ET_MSC_LOGGER_SYNC_EXIT
}

void PSendDataReplPort_receivedData_broadcast(const PSendDataReplPort* self, DDataBuffer* data__et) {
	int i;
	ET_MSC_LOGGER_SYNC_ENTRY("PSendDataReplPort", "receivedData")
	for (i=0; i<((etReplPort*)self)->size; ++i) {
		etPort_sendMessage((&((etReplPort*)self)->ports[i].port), PSendData_OUT_receivedData, sizeof(DDataBuffer), data__et);
		ET_MSC_LOGGER_ASYNC_OUT(((etReplPort*)self)->ports[i].port.myInstName, "receivedData", ((etReplPort*)self)->ports[i].port.peerInstName)
	}
	ET_MSC_LOGGER_SYNC_EXIT
}

void PSendDataReplPort_receivedData(const PSendDataReplPort* self, int idx__et, DDataBuffer* data__et) {
	ET_MSC_LOGGER_SYNC_ENTRY("PSendDataReplPort", "receivedData")
	if (0<=idx__et && idx__et<((etReplPort*)self)->size) {
		etPort_sendMessage((&((etReplPort*)self)->ports[idx__et].port), PSendData_OUT_receivedData, sizeof(DDataBuffer), data__et);
		ET_MSC_LOGGER_ASYNC_OUT(((etReplPort*)self)->ports[idx__et].port.myInstName, "receivedData", ((etReplPort*)self)->ports[idx__et].port.peerInstName)
	}
	ET_MSC_LOGGER_SYNC_EXIT
}

etInt32 PSendDataReplPort_getReplication(const PSendDataReplPort* self) {
	return ((etReplPort*)self)->size;
}



void PSendDataConjPort_sendData(const PSendDataConjPort* self, DDataBuffer* data__et) {
	ET_MSC_LOGGER_SYNC_ENTRY("PSendDataConjPort", "sendData")
		etPort_sendMessage(self, PSendData_IN_sendData, sizeof(DDataBuffer), data__et);
		ET_MSC_LOGGER_ASYNC_OUT(self->myInstName, "sendData", self->peerInstName)
	ET_MSC_LOGGER_SYNC_EXIT
}

void PSendDataConjReplPort_sendData_broadcast(const PSendDataConjReplPort* self, DDataBuffer* data__et) {
	int i;
	ET_MSC_LOGGER_SYNC_ENTRY("PSendDataConjReplPort", "sendData")
	for (i=0; i<((etReplPort*)self)->size; ++i) {
		etPort_sendMessage((&((etReplPort*)self)->ports[i].port), PSendData_IN_sendData, sizeof(DDataBuffer), data__et);
		ET_MSC_LOGGER_ASYNC_OUT(((etReplPort*)self)->ports[i].port.myInstName, "sendData", ((etReplPort*)self)->ports[i].port.peerInstName)
	}
	ET_MSC_LOGGER_SYNC_EXIT
}

void PSendDataConjReplPort_sendData(const PSendDataConjReplPort* self, int idx__et, DDataBuffer* data__et) {
	ET_MSC_LOGGER_SYNC_ENTRY("PSendDataConjReplPort", "sendData")
	if (0<=idx__et && idx__et<((etReplPort*)self)->size) {
		etPort_sendMessage((&((etReplPort*)self)->ports[idx__et].port), PSendData_IN_sendData, sizeof(DDataBuffer), data__et);
		ET_MSC_LOGGER_ASYNC_OUT(((etReplPort*)self)->ports[idx__et].port.myInstName, "sendData", ((etReplPort*)self)->ports[idx__et].port.peerInstName)
	}
	ET_MSC_LOGGER_SYNC_EXIT
}


void PSendDataConjPort_forRingControl(const PSendDataConjPort* self) {
	ET_MSC_LOGGER_SYNC_ENTRY("PSendDataConjPort", "forRingControl")
		etPort_sendMessage(self, PSendData_IN_forRingControl, 0, NULL);
		ET_MSC_LOGGER_ASYNC_OUT(self->myInstName, "forRingControl", self->peerInstName)
	ET_MSC_LOGGER_SYNC_EXIT
}

void PSendDataConjReplPort_forRingControl_broadcast(const PSendDataConjReplPort* self) {
	int i;
	ET_MSC_LOGGER_SYNC_ENTRY("PSendDataConjReplPort", "forRingControl")
	for (i=0; i<((etReplPort*)self)->size; ++i) {
		etPort_sendMessage((&((etReplPort*)self)->ports[i].port), PSendData_IN_forRingControl, 0, NULL);
		ET_MSC_LOGGER_ASYNC_OUT(((etReplPort*)self)->ports[i].port.myInstName, "forRingControl", ((etReplPort*)self)->ports[i].port.peerInstName)
	}
	ET_MSC_LOGGER_SYNC_EXIT
}

void PSendDataConjReplPort_forRingControl(const PSendDataConjReplPort* self, int idx__et) {
	ET_MSC_LOGGER_SYNC_ENTRY("PSendDataConjReplPort", "forRingControl")
	if (0<=idx__et && idx__et<((etReplPort*)self)->size) {
		etPort_sendMessage((&((etReplPort*)self)->ports[idx__et].port), PSendData_IN_forRingControl, 0, NULL);
		ET_MSC_LOGGER_ASYNC_OUT(((etReplPort*)self)->ports[idx__et].port.myInstName, "forRingControl", ((etReplPort*)self)->ports[idx__et].port.peerInstName)
	}
	ET_MSC_LOGGER_SYNC_EXIT
}

etInt32 PSendDataConjReplPort_getReplication(const PSendDataConjReplPort* self) {
	return ((etReplPort*)self)->size;
}



/*--------------------- debug helpers */

/* message names as strings for debugging (generate MSC) */
static const char* const PSendData_messageStrings[] = {"MIN", "receivedData","sendData", "forRingControl", "MAX"};

const char* PSendData_getMessageString(int msg_id) {
	if (msg_id<PSendData_MSG_MIN || msg_id>PSendData_MSG_MAX+1){
		/* id out of range */
		return "Message ID out of range";
	}
	else{
		return PSendData_messageStrings[msg_id];
	}
}
