/**
 * @author generated by eTrice
 *
 * Source File of ActorClass FlatReplication
 *
 */

#include "FlatReplication.h"

#include "modelbase/etActor.h"
#include "debugging/etLogger.h"
#include "debugging/etMSCLogger.h"
#include "etUnit/etUnit.h"
#include "base/etMemory.h"

#include "room/basic/service/tcp/PTcpControl.h"
#include "room/basic/service/tcp/PTcpPayload.h"
#include "room/basic/service/timing/PTimer.h"
#include "TrafficLight/PTrafficLightController.h"
#include "TrafficLight/PTrafficLightInterface.h"

#include "FlatReplication_Utils.h"


/* interface item IDs */
/* empty enum not generated */


void FlatReplication_init(FlatReplication* self){
	ET_MSC_LOGGER_SYNC_ENTRY("FlatReplication", "init")
	ET_MSC_LOGGER_SYNC_EXIT
}


void FlatReplication_receiveMessage(void* self, const void* ifitem, const etMessage* msg){
	ET_MSC_LOGGER_SYNC_ENTRY("FlatReplication", "_receiveMessage")

	ET_MSC_LOGGER_SYNC_EXIT
}


/*--------------------- user constructor/destructor ---------------------*/

/*--------------------- operations ---------------------*/

