/**
 * @author generated by eTrice
 *
 * Utils File of ActorClass HierarchicalReplication
 *
 */

#ifndef _TRAFFICLIGHT_HIERARCHICALREPLICATION_UTILS_H_
#define _TRAFFICLIGHT_HIERARCHICALREPLICATION_UTILS_H_

#include "TrafficLight/HierarchicalReplication.h"

/*
 * access macros for ports, operations and attributes
*/

/* simple event ports */

/* data receive ports */

/* data send ports */

/* saps */

/* replicated event ports */

/* services */

/* operations */

/* attributes */

/* port operations */

#endif /* _TRAFFICLIGHT_HIERARCHICALREPLICATION_UTILS_H_ */

