/**
 * @author generated by eTrice
 *
 * Utils File of ActorClass PedestrianTrafficLightController
 *
 */

#ifndef _TRAFFICLIGHT_PEDESTRIANTRAFFICLIGHTCONTROLLER_UTILS_H_
#define _TRAFFICLIGHT_PEDESTRIANTRAFFICLIGHTCONTROLLER_UTILS_H_

#include "TrafficLight/PedestrianTrafficLightController.h"

/*
 * access macros for ports, operations and attributes
*/

/* simple event ports */
#define fct_doneStandby() PTrafficLightControllerPort_doneStandby(&self->constData->fct)
#define fct_doneStart() PTrafficLightControllerPort_doneStart(&self->constData->fct)
#define fct_doneStop() PTrafficLightControllerPort_doneStop(&self->constData->fct)
#define tlInterface_connect(data) PTrafficLightInterfaceConjPort_connect(&self->constData->tlInterface, data)
#define tlInterface_setCarRed(data) PTrafficLightInterfaceConjPort_setCarRed(&self->constData->tlInterface, data)
#define tlInterface_setCarYellow(data) PTrafficLightInterfaceConjPort_setCarYellow(&self->constData->tlInterface, data)
#define tlInterface_setCarGreen(data) PTrafficLightInterfaceConjPort_setCarGreen(&self->constData->tlInterface, data)
#define tlInterface_setPedRed(data) PTrafficLightInterfaceConjPort_setPedRed(&self->constData->tlInterface, data)
#define tlInterface_setPedGreen(data) PTrafficLightInterfaceConjPort_setPedGreen(&self->constData->tlInterface, data)
#define tlInterface_setRequestButtonActive(data) PTrafficLightInterfaceConjPort_setRequestButtonActive(&self->constData->tlInterface, data)

/* data receive ports */

/* data send ports */

/* saps */
#define to_startTimer(data) PTimerConjPort_startTimer(&self->constData->to, data)
#define to_startTimeout(data) PTimerConjPort_startTimeout(&self->constData->to, data)
#define to_kill() PTimerConjPort_kill(&self->constData->to)

/* replicated event ports */

/* services */

/* operations */

/* attributes */
#define timeBase (self->timeBase)

/* port operations */

#endif /* _TRAFFICLIGHT_PEDESTRIANTRAFFICLIGHTCONTROLLER_UTILS_H_ */

