/**
 * @author generated by eTrice
 *
 * Utils File of ProtocolClass PTrafficLightInterface
 * 
 */

#ifndef _TRAFFICLIGHT_PTRAFFICLIGHTINTERFACE_UTILS_H_
#define _TRAFFICLIGHT_PTRAFFICLIGHTINTERFACE_UTILS_H_

#include "TrafficLight/PTrafficLightInterface.h"

/*
 * access macros for operations and attributes
*/


#endif /* _TRAFFICLIGHT_PTRAFFICLIGHTINTERFACE_UTILS_H_ */

