/**
 * @author generated by eTrice
 *
 * Utils File of ProtocolClass PTrafficLightController
 * 
 */

#ifndef _TRAFFICLIGHT_PTRAFFICLIGHTCONTROLLER_UTILS_H_
#define _TRAFFICLIGHT_PTRAFFICLIGHTCONTROLLER_UTILS_H_

#include "TrafficLight/PTrafficLightController.h"

/*
 * access macros for operations and attributes
*/


#endif /* _TRAFFICLIGHT_PTRAFFICLIGHTCONTROLLER_UTILS_H_ */

