/**
 * @author generated by eTrice
 *
 * Source File of ActorClass SingleTrafficLight
 *
 */

#include "SingleTrafficLight.h"

#include "modelbase/etActor.h"
#include "debugging/etLogger.h"
#include "debugging/etMSCLogger.h"
#include "etUnit/etUnit.h"
#include "base/etMemory.h"

#include "room/basic/service/tcp/PTcpControl.h"
#include "room/basic/service/tcp/PTcpPayload.h"
#include "room/basic/service/timing/PTimer.h"
#include "TrafficLight/PTrafficLightController.h"
#include "TrafficLight/PTrafficLightInterface.h"

#include "SingleTrafficLight_Utils.h"


/* interface item IDs */
/* empty enum not generated */


void SingleTrafficLight_init(SingleTrafficLight* self){
	ET_MSC_LOGGER_SYNC_ENTRY("SingleTrafficLight", "init")
	ET_MSC_LOGGER_SYNC_EXIT
}


void SingleTrafficLight_receiveMessage(void* self, const void* ifitem, const etMessage* msg){
	ET_MSC_LOGGER_SYNC_ENTRY("SingleTrafficLight", "_receiveMessage")

	ET_MSC_LOGGER_SYNC_EXIT
}


/*--------------------- user constructor/destructor ---------------------*/

/*--------------------- operations ---------------------*/

