/**
 * @author generated by eTrice
 *
 * Header File of ActorClass TestApplication
 *
 */

#ifndef _TRAFFICLIGHT_TESTAPPLICATION_H_
#define _TRAFFICLIGHT_TESTAPPLICATION_H_

#include "etDatatypes.h"
#include "messaging/etMessage.h"

/* include all referenced room classes */
#include "room/basic/service/timing/PTimer.h"
#include "TrafficLight/PTrafficLightController.h"
#include "TrafficLight/PTrafficLightInterface.h"


typedef struct TestApplication TestApplication;

/* const part of ActorClass (ROM) */
typedef struct TestApplication_const {
	const char* instName;

	/* simple ports */

	/* data receive ports */

	/* saps */

	/* replicated ports */

	/* services */
} TestApplication_const;


/* variable part of ActorClass (RAM) */
struct TestApplication {
	const TestApplication_const* const constData;

	/* data send ports */

	/*--------------------- attributes ---------------------*/

};

void TestApplication_init(TestApplication* self);

void TestApplication_receiveMessage(void* self, const void* ifitem, const etMessage* msg);


/*--------------------- user constructor/destructor ---------------------*/

/*--------------------- operations ---------------------*/


#endif /* _TRAFFICLIGHT_TESTAPPLICATION_H_ */

