/**
 * @author generated by eTrice
 *
 * Header File of ActorClass TrafficLightControllerTestHarness
 *
 */

#ifndef _TRAFFICLIGHT_TRAFFICLIGHTCONTROLLERTESTHARNESS_H_
#define _TRAFFICLIGHT_TRAFFICLIGHTCONTROLLERTESTHARNESS_H_

#include "etDatatypes.h"
#include "messaging/etMessage.h"

/* include all referenced room classes */
#include "room/basic/service/timing/PTimer.h"
#include "TrafficLight/PTrafficLightController.h"
#include "TrafficLight/PTrafficLightInterface.h"


typedef struct TrafficLightControllerTestHarness TrafficLightControllerTestHarness;

/* const part of ActorClass (ROM) */
typedef struct TrafficLightControllerTestHarness_const {
	const char* instName;

	/* simple ports */
	const PTrafficLightControllerConjPort fct;
	const PTrafficLightInterfacePort tlInterface;

	/* data receive ports */

	/* saps */
	const PTimerConjPort to;

	/* replicated ports */

	/* services */
} TrafficLightControllerTestHarness_const;


/* constant for state machine data */
#define TRAFFICLIGHTCONTROLLERTESTHARNESS_HISTORY_SIZE 2

/* variable part of ActorClass (RAM) */
struct TrafficLightControllerTestHarness {
	const TrafficLightControllerTestHarness_const* const constData;

	/* data send ports */

	/*--------------------- attributes ---------------------*/
	 int32 counter;


	/* state machine variables */
	etInt16 state;
	etInt16 history[TRAFFICLIGHTCONTROLLERTESTHARNESS_HISTORY_SIZE];
};

void TrafficLightControllerTestHarness_init(TrafficLightControllerTestHarness* self);

void TrafficLightControllerTestHarness_receiveMessage(void* self, const void* ifitem, const etMessage* msg);


/*--------------------- user constructor/destructor ---------------------*/

/*--------------------- operations ---------------------*/


#endif /* _TRAFFICLIGHT_TRAFFICLIGHTCONTROLLERTESTHARNESS_H_ */

