/**
 * @author generated by eTrice
 *
 * Header File of ActorClass TrafficLightHeadquarters
 *
 */

#ifndef _TRAFFICLIGHT_TRAFFICLIGHTHEADQUARTERS_H_
#define _TRAFFICLIGHT_TRAFFICLIGHTHEADQUARTERS_H_

#include "etDatatypes.h"
#include "messaging/etMessage.h"

/* include all referenced room classes */
#include "room/basic/service/timing/PTimer.h"
#include "TrafficLight/PTrafficLightController.h"


typedef struct TrafficLightHeadquarters TrafficLightHeadquarters;

/* const part of ActorClass (ROM) */
typedef struct TrafficLightHeadquarters_const {
	const char* instName;

	/* simple ports */

	/* data receive ports */

	/* saps */
	const PTimerConjPort to;

	/* replicated ports */
	const etReplPort controllers;

	/* services */
} TrafficLightHeadquarters_const;


/* constant for state machine data */
#define TRAFFICLIGHTHEADQUARTERS_HISTORY_SIZE 2

/* variable part of ActorClass (RAM) */
struct TrafficLightHeadquarters {
	const TrafficLightHeadquarters_const* const constData;

	/* data send ports */

	/*--------------------- attributes ---------------------*/


	/* state machine variables */
	etInt16 state;
	etInt16 history[TRAFFICLIGHTHEADQUARTERS_HISTORY_SIZE];
};

void TrafficLightHeadquarters_init(TrafficLightHeadquarters* self);

void TrafficLightHeadquarters_receiveMessage(void* self, const void* ifitem, const etMessage* msg);


/*--------------------- user constructor/destructor ---------------------*/

/*--------------------- operations ---------------------*/


#endif /* _TRAFFICLIGHT_TRAFFICLIGHTHEADQUARTERS_H_ */

