/**
 * @author generated by eTrice
 *
 * Utils File of ActorClass TrafficLightInterface
 *
 */

#ifndef _TRAFFICLIGHT_TRAFFICLIGHTINTERFACE_UTILS_H_
#define _TRAFFICLIGHT_TRAFFICLIGHTINTERFACE_UTILS_H_

#include "TrafficLight/TrafficLightInterface.h"

/*
 * access macros for ports, operations and attributes
*/

/* simple event ports */
#define fct_connected() PTrafficLightInterfacePort_connected(&self->constData->fct)
#define fct_pressedRequestButton() PTrafficLightInterfacePort_pressedRequestButton(&self->constData->fct)
#define ctrl_connect(data) PTcpControlConjPort_connect(&self->constData->ctrl, data)
#define ctrl_disconnect() PTcpControlConjPort_disconnect(&self->constData->ctrl)
#define payload_dataPackage(data) PTcpPayloadConjPort_dataPackage(&self->constData->payload, data)

/* data receive ports */

/* data send ports */

/* saps */

/* replicated event ports */

/* services */

/* operations */
#define sendPayloadString(data) TrafficLightInterface_sendPayloadString(self, data)
#define sendOnOffCommand(lightString, status) TrafficLightInterface_sendOnOffCommand(self, lightString, status)

/* attributes */

/* port operations */

#endif /* _TRAFFICLIGHT_TRAFFICLIGHTINTERFACE_UTILS_H_ */

