/**
 * @author generated by eTrice
 *
 * Header File of ActorClass TrafficLightInterfaceStub
 *
 */

#ifndef _TRAFFICLIGHT_TRAFFICLIGHTINTERFACESTUB_H_
#define _TRAFFICLIGHT_TRAFFICLIGHTINTERFACESTUB_H_

#include "etDatatypes.h"
#include "messaging/etMessage.h"

/* include all referenced room classes */
#include "room/basic/service/timing/PTimer.h"
#include "TrafficLight/PTrafficLightInterface.h"


typedef struct TrafficLightInterfaceStub TrafficLightInterfaceStub;

/* const part of ActorClass (ROM) */
typedef struct TrafficLightInterfaceStub_const {
	const char* instName;

	/* simple ports */
	const PTrafficLightInterfacePort fct;

	/* data receive ports */

	/* saps */
	const PTimerConjPort to;

	/* replicated ports */

	/* services */
} TrafficLightInterfaceStub_const;


/* constant for state machine data */
#define TRAFFICLIGHTINTERFACESTUB_HISTORY_SIZE 2

/* variable part of ActorClass (RAM) */
struct TrafficLightInterfaceStub {
	const TrafficLightInterfaceStub_const* const constData;

	/* data send ports */

	/*--------------------- attributes ---------------------*/


	/* state machine variables */
	etInt16 state;
	etInt16 history[TRAFFICLIGHTINTERFACESTUB_HISTORY_SIZE];
};

void TrafficLightInterfaceStub_init(TrafficLightInterfaceStub* self);

void TrafficLightInterfaceStub_receiveMessage(void* self, const void* ifitem, const etMessage* msg);


/*--------------------- user constructor/destructor ---------------------*/

/*--------------------- operations ---------------------*/


#endif /* _TRAFFICLIGHT_TRAFFICLIGHTINTERFACESTUB_H_ */

