/**
 * @author generated by eTrice
 *
 * Source File of ActorClass TrafficLightHeadquarters
 *
 */

#include "TrafficLightHeadquarters.h"

#include "modelbase/etActor.h"
#include "debugging/etLogger.h"
#include "debugging/etMSCLogger.h"
#include "etUnit/etUnit.h"
#include "base/etMemory.h"

#include "room/basic/service/timing/PTimer.h"
#include "TrafficLight/PTrafficLightController.h"

#include "TrafficLightHeadquarters_Utils.h"


/* interface item IDs */
enum interface_items {
	IFITEM_controllers = 1,
	IFITEM_to = 2
};

/* state IDs */
enum state_ids {
	NO_STATE = 0,
	STATE_TOP = 1,
	STATE_Standby = 2,
	STATE_Running = 3,
	STATE_Stopped = 4,
	STATE_MAX = 5
};

/* transition chains */
enum ChainIDs {
	CHAIN_TRANS_INITIAL_TO__Standby = 1,
	CHAIN_TRANS_tr0_FROM_Standby_TO_Running_BY_timeoutto = 2,
	CHAIN_TRANS_tr1_FROM_Running_TO_Stopped_BY_timeoutto = 3
};

/* triggers */
enum triggers {
	POLLING = 0,
	TRIG_controllers__doneStandby = IFITEM_controllers + EVT_SHIFT*PTrafficLightController_OUT_doneStandby,
	TRIG_controllers__doneStart = IFITEM_controllers + EVT_SHIFT*PTrafficLightController_OUT_doneStart,
	TRIG_controllers__doneStop = IFITEM_controllers + EVT_SHIFT*PTrafficLightController_OUT_doneStop,
	TRIG_to__timeout = IFITEM_to + EVT_SHIFT*PTimer_OUT_timeout
};

/* state names */
static char* stateStrings[] = {"<no state>","<top>","Standby",
"Running",
"Stopped"
};

static void setState(TrafficLightHeadquarters* self, etInt16 new_state) {
	self->state = new_state;
	ET_MSC_LOGGER_CHANGE_STATE(self->constData->instName, stateStrings[new_state])
}

static etInt16 getState(TrafficLightHeadquarters* self) {
	return self->state;
}

/* Entry and Exit Codes */
static void entry_Standby(TrafficLightHeadquarters* self) {
	int n = PTrafficLightControllerReplPort_getReplication(&self->constData->controllers);
	int i;
	
	printf("hq: number of connections is %d\n", n);
	
	for (i=0; i<n; ++i)
		controllers_standby(i, 4441+i);
	
	to_startTimeout(200*10);
}
static void entry_Running(TrafficLightHeadquarters* self) {
	controllers_start_broadcast();
	to_startTimeout(200*10);
}
static void entry_Stopped(TrafficLightHeadquarters* self) {
	controllers_stop_broadcast();
}

/* Action Codes */

/* State Switch Methods */
/**
 * calls exit codes while exiting from the current state to one of its
 * parent states while remembering the history
 * @param current__et - the current state
 * @param to - the final parent state
 */
static void exitTo(TrafficLightHeadquarters* self, etInt16 current__et, etInt16 to) {
	while (current__et!=to) {
		switch (current__et) {
			case STATE_Standby:
				self->history[STATE_TOP] = STATE_Standby;
				current__et = STATE_TOP;
				break;
			case STATE_Running:
				self->history[STATE_TOP] = STATE_Running;
				current__et = STATE_TOP;
				break;
			case STATE_Stopped:
				self->history[STATE_TOP] = STATE_Stopped;
				current__et = STATE_TOP;
				break;
			default:
				/* should not occur */
				break;
		}
	}
}

/**
 * calls action, entry and exit codes along a transition chain. The generic data are cast to typed data
 * matching the trigger of this chain. The ID of the final state is returned
 * @param chain__et - the chain ID
 * @param generic_data__et - the generic data pointer
 * @return the +/- ID of the final state either with a positive sign, that indicates to execute the state's entry code, or a negative sign vice versa
 */
static etInt16 executeTransitionChain(TrafficLightHeadquarters* self, int chain__et, const InterfaceItemBase* ifitem, void* generic_data__et) {
	switch (chain__et) {
		case CHAIN_TRANS_INITIAL_TO__Standby:
		{
			return STATE_Standby;
		}
		case CHAIN_TRANS_tr0_FROM_Standby_TO_Running_BY_timeoutto:
		{
			return STATE_Running;
		}
		case CHAIN_TRANS_tr1_FROM_Running_TO_Stopped_BY_timeoutto:
		{
			return STATE_Stopped;
		}
			default:
				/* should not occur */
				break;
	}
	return NO_STATE;
}

/**
 * calls entry codes while entering a state's history. The ID of the final leaf state is returned
 * @param state__et - the state which is entered
 * @return - the ID of the final leaf state
 */
static etInt16 enterHistory(TrafficLightHeadquarters* self, etInt16 state__et) {
	etBool skip_entry__et = ET_FALSE;
	if (state__et >= STATE_MAX) {
		state__et = (etInt16) (state__et - STATE_MAX);
		skip_entry__et = ET_TRUE;
	}
	while (ET_TRUE) {
		switch (state__et) {
			case STATE_Standby:
				if (!(skip_entry__et)) entry_Standby(self);
				/* in leaf state: return state id */
				return STATE_Standby;
			case STATE_Running:
				if (!(skip_entry__et)) entry_Running(self);
				/* in leaf state: return state id */
				return STATE_Running;
			case STATE_Stopped:
				if (!(skip_entry__et)) entry_Stopped(self);
				/* in leaf state: return state id */
				return STATE_Stopped;
			case STATE_TOP:
				state__et = self->history[STATE_TOP];
				break;
			default:
				/* should not occur */
				break;
		}
		skip_entry__et = ET_FALSE;
	}
	/* return NO_STATE; // required by CDT but detected as unreachable by JDT because of while (true) */
}

static void TrafficLightHeadquarters_executeInitTransition(TrafficLightHeadquarters* self) {
	int chain__et = CHAIN_TRANS_INITIAL_TO__Standby;
	etInt16 next__et = executeTransitionChain(self, chain__et, NULL, NULL);
	next__et = enterHistory(self, next__et);
	setState(self, next__et);
}

/* receiveEvent contains the main implementation of the FSM */
static void TrafficLightHeadquarters_receiveEventInternal(TrafficLightHeadquarters* self, InterfaceItemBase* ifitem, int localId, int evt, void* generic_data__et) {
	int trigger__et = localId + EVT_SHIFT*evt;
	int chain__et = NOT_CAUGHT;
	etInt16 catching_state__et = NO_STATE;
	((void)trigger__et);	/* avoids unused warning */

	if (!handleSystemEvent(ifitem, evt, generic_data__et)) {
		switch (getState(self)) {
		    case STATE_Standby:
		        switch(trigger__et) {
		                case TRIG_to__timeout:
		                    {
		                        chain__et = CHAIN_TRANS_tr0_FROM_Standby_TO_Running_BY_timeoutto;
		                        catching_state__et = STATE_TOP;
		                    }
		                break;
		                default:
		                    /* should not occur */
		                    break;
		        }
		        break;
		    case STATE_Running:
		        switch(trigger__et) {
		                case TRIG_to__timeout:
		                    {
		                        chain__et = CHAIN_TRANS_tr1_FROM_Running_TO_Stopped_BY_timeoutto;
		                        catching_state__et = STATE_TOP;
		                    }
		                break;
		                default:
		                    /* should not occur */
		                    break;
		        }
		        break;
		    case STATE_Stopped:
		        break;
		    default:
		        /* should not occur */
		        break;
		}
	}
	if (chain__et != NOT_CAUGHT) {
		exitTo(self, getState(self), catching_state__et);
		{
			etInt16 next__et = executeTransitionChain(self, chain__et, ifitem, generic_data__et);
			next__et = enterHistory(self, next__et);
			setState(self, next__et);
		}
	}
}
static void TrafficLightHeadquarters_receiveEvent(TrafficLightHeadquarters* self, InterfaceItemBase* ifitem, int evt, void* generic_data__et) {
	int localId = (ifitem==NULL)? 0 : ifitem->localId;
	TrafficLightHeadquarters_receiveEventInternal(self, ifitem, localId, evt, generic_data__et);
}

void TrafficLightHeadquarters_init(TrafficLightHeadquarters* self){
	ET_MSC_LOGGER_SYNC_ENTRY("TrafficLightHeadquarters", "init")
	self->state = STATE_TOP;
	{
		int i;
		for (i=0; i<TRAFFICLIGHTHEADQUARTERS_HISTORY_SIZE; ++i)
			self->history[i] = NO_STATE;
	}
	TrafficLightHeadquarters_executeInitTransition(self);
	ET_MSC_LOGGER_SYNC_EXIT
}


void TrafficLightHeadquarters_receiveMessage(void* self, const void* ifitem, const etMessage* msg){
	ET_MSC_LOGGER_SYNC_ENTRY("TrafficLightHeadquarters", "_receiveMessage")
	TrafficLightHeadquarters_receiveEvent(self, (etPort*)ifitem, msg->evtID, (void*)(((char*)msg)+MEM_CEIL(sizeof(etMessage))));

	ET_MSC_LOGGER_SYNC_EXIT
}


/*--------------------- user constructor/destructor ---------------------*/

/*--------------------- operations ---------------------*/

