/**
 * @author generated by eTrice
 *
 * Utils File of ActorClass TrafficLightHeadquarters
 *
 */

#ifndef _TRAFFICLIGHT_TRAFFICLIGHTHEADQUARTERS_UTILS_H_
#define _TRAFFICLIGHT_TRAFFICLIGHTHEADQUARTERS_UTILS_H_

#include "TrafficLight/TrafficLightHeadquarters.h"

/*
 * access macros for ports, operations and attributes
*/

/* simple event ports */

/* data receive ports */

/* data send ports */

/* saps */
#define to_startTimer(data) PTimerConjPort_startTimer(&self->constData->to, data)
#define to_startTimeout(data) PTimerConjPort_startTimeout(&self->constData->to, data)
#define to_kill() PTimerConjPort_kill(&self->constData->to)

/* replicated event ports */
#define ifitem_index (((etReplSubPort*)ifitem)->index)
#define controllers_standby_broadcast(data) PTrafficLightControllerConjReplPort_standby_broadcast(&self->constData->controllers, data)
#define controllers_standby(idx, data) PTrafficLightControllerConjReplPort_standby(&self->constData->controllers, idx, data)
#define controllers_start_broadcast() PTrafficLightControllerConjReplPort_start_broadcast(&self->constData->controllers)
#define controllers_start(idx) PTrafficLightControllerConjReplPort_start(&self->constData->controllers, idx)
#define controllers_stop_broadcast() PTrafficLightControllerConjReplPort_stop_broadcast(&self->constData->controllers)
#define controllers_stop(idx) PTrafficLightControllerConjReplPort_stop(&self->constData->controllers, idx)

/* services */

/* operations */

/* attributes */

/* port operations */

#endif /* _TRAFFICLIGHT_TRAFFICLIGHTHEADQUARTERS_UTILS_H_ */

