/**
 * @author generated by eTrice
 *
 * Utils File of ActorClass TrafficLightControllerTestHarness
 *
 */

#ifndef _TRAFFICLIGHT_TRAFFICLIGHTCONTROLLERTESTHARNESS_UTILS_H_
#define _TRAFFICLIGHT_TRAFFICLIGHTCONTROLLERTESTHARNESS_UTILS_H_

#include "TrafficLight/TrafficLightControllerTestHarness.h"

/*
 * access macros for ports, operations and attributes
*/

/* simple event ports */
#define fct_standby(data) PTrafficLightControllerConjPort_standby(&self->constData->fct, data)
#define fct_start() PTrafficLightControllerConjPort_start(&self->constData->fct)
#define fct_stop() PTrafficLightControllerConjPort_stop(&self->constData->fct)
#define tlInterface_connected() PTrafficLightInterfacePort_connected(&self->constData->tlInterface)
#define tlInterface_pressedRequestButton() PTrafficLightInterfacePort_pressedRequestButton(&self->constData->tlInterface)

/* data receive ports */

/* data send ports */

/* saps */
#define to_startTimer(data) PTimerConjPort_startTimer(&self->constData->to, data)
#define to_startTimeout(data) PTimerConjPort_startTimeout(&self->constData->to, data)
#define to_kill() PTimerConjPort_kill(&self->constData->to)

/* replicated event ports */

/* services */

/* operations */

/* attributes */
#define counter (self->counter)

/* port operations */

#endif /* _TRAFFICLIGHT_TRAFFICLIGHTCONTROLLERTESTHARNESS_UTILS_H_ */

